version: '3.8'

services:
  esercizio-3-mini-sito-multilingua:
    image: php:8.3-apache
    container_name: mini-sito-multilingua
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html