version: '3.8'

services:
  backend-esercizio-email:
    image: php:8.3-apache
    container_name: backend-esercizio-email
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html